// Authoritative audit item catalogue for audit.speculaone.com.
// Moved verbatim out of App.jsx so it can be imported without React,
// which is what lets the scoring framework validate against the real
// source instead of a second hand-maintained list of item ids.

export const SECTIONS = [
  { id: 'pre', label: 'Pre-Arrival & Website', icon: '◈', facility: null, items: [
    { id: 'PRE-01', label: 'Branding consistent and luxury-appropriate', minStars: 4 },
    { id: 'PRE-02', label: 'Professional photography and video', minStars: 4 },
    { id: 'PRE-03', label: 'Booking process simple and transparent', minStars: 4 },
    { id: 'PRE-04', label: 'Mobile optimized and fast loading', minStars: 4 },
    { id: 'PRE-05', label: 'Confirmation email professional and on-brand', minStars: 4 },
    { id: 'PRE-06', label: 'Pre-arrival preference questionnaire sent', minStars: 5 },
    { id: 'PRE-07', label: 'Dedicated concierge contact provided pre-stay', minStars: 6 },
    { id: 'PRE-08', label: 'Overall marketing presence strong and consistent', minStars: 4 },
    { id: 'PRE-09', label: 'Website quality — design, content, ease of use', minStars: 4 },
    { id: 'PRE-10', label: 'Phone call to reception — responsiveness and helpfulness', minStars: 4 },
    { id: 'PRE-11', label: 'Email response — timeliness and quality', minStars: 4 },
    { id: 'PRE-12', label: 'Social media presence active and on-brand', minStars: 4 },
    { id: 'PRE-13', label: 'List of bookable extras/services sent pre-arrival', minStars: 5 },
  ]},
  { id: 'arrival', label: 'Arrival & Entrance', icon: '→', facility: null, items: [
    { id: 'ARR-01', label: 'Exterior clean and well-maintained', minStars: 4 },
    { id: 'ARR-02', label: 'Guest greeted within 30 seconds', minStars: 4 },
    { id: 'ARR-03', label: 'Luggage assistance offered proactively', minStars: 4 },
    { id: 'ARR-04', label: 'Pleasant atmosphere — scent, music, temperature', minStars: 4 },
    { id: 'ARR-05', label: 'Doorman or valet present', minStars: 5 },
    { id: 'ARR-06', label: 'Welcome drink or cold towel offered', minStars: 5 },
    { id: 'ARR-07', label: 'Bespoke welcome ritual or experience', minStars: 6 },
    { id: 'ARR-08', label: 'Disabled access available and functional', minStars: 4 },
    { id: 'ARR-09', label: 'Lighting appropriate throughout', minStars: 4 },
    { id: 'ARR-10', label: 'Furniture in good condition', minStars: 4 },
    { id: 'ARR-11', label: 'Cushions fluffed, no visible dust', minStars: 4 },
    { id: 'ARR-12', label: 'Music/mood present and at appropriate volume', minStars: 4 },
  ]},
  { id: 'reception', label: 'Reception & Check-in', icon: '⊡', facility: null, items: [
    { id: 'REC-01', label: 'Wait time under 3 minutes', minStars: 4 },
    { id: 'REC-02', label: 'Guest addressed by name', minStars: 4 },
    { id: 'REC-03', label: 'Eye contact and genuine smile', minStars: 4 },
    { id: 'REC-04', label: 'Staff knowledgeable — local tips and amenities', minStars: 4 },
    { id: 'REC-05', label: 'Room preference acknowledged or upgraded', minStars: 5 },
    { id: 'REC-06', label: 'Private or in-room check-in offered', minStars: 6 },
    { id: 'REC-07', label: 'Personal butler or liaison introduced', minStars: 6 },
    { id: 'REC-08', label: 'Front desk free of clutter', minStars: 4 },
    { id: 'REC-09', label: 'Total check-in time reasonable', minStars: 4 },
    { id: 'REC-10', label: 'Tour offered or facilities map explained', minStars: 4 },
    { id: 'REC-11', label: 'Reservation delivered exactly as confirmed: room type, rate, dates and stated requirements', minStars: 4 },
  ]},
  { id: 'room', label: 'Room Quality', icon: '□', facility: null, items: [
    { id: 'RM-01', label: 'Surfaces dust-free, mirrors spotless', minStars: 4 },
    { id: 'RM-02', label: 'No hair, stains, or odors', minStars: 4 },
    { id: 'RM-03', label: 'All lights and technology functioning', minStars: 4 },
    { id: 'RM-04', label: 'Bedding high quality and fresh', minStars: 4 },
    { id: 'RM-05', label: 'Noise levels acceptable', minStars: 4 },
    { id: 'RM-06', label: 'Premium minibar and luxury amenities', minStars: 5 },
    { id: 'RM-07', label: 'Welcome gift or personal note present', minStars: 5 },
    { id: 'RM-08', label: 'Guest preferences pre-applied (pillow, temp)', minStars: 6 },
    { id: 'RM-09', label: 'Nothing in the room visibly outdated', minStars: 4 },
    { id: 'RM-10', label: 'Minibar cleared/reset since last guest', minStars: 4 },
  ]},
  { id: 'facilities', label: 'Facilities', icon: '⚙', facility: null, items: [
    { id: 'FAC-01', label: 'Overall exterior condition well maintained', minStars: 4 },
    { id: 'FAC-02', label: 'Overall interior condition well maintained', minStars: 4 },
    { id: 'FAC-03', label: 'General maintenance standards high', minStars: 4 },
    { id: 'FAC-04', label: 'Gym equipment modern and well maintained', minStars: 4 },
    { id: 'FAC-05', label: 'Gym access cost clearly disclosed (free or paid)', minStars: 4 },
    { id: 'FAC-06', label: 'Gym has a view or pleasant environment', minStars: 5 },
  ]},
  { id: 'safety', label: 'Safety, Security & Integrity', icon: '⊗', facility: null, items: [
    { id: 'SAF-01', label: 'Emergency exits, fire safety equipment and evacuation information present, unobstructed and current', minStars: 4 },
    { id: 'SAF-02', label: 'Guest room locks, secondary security and in-room safe function correctly', minStars: 4 },
    { id: 'SAF-03', label: 'Guests treated with respect and professionalism, without discrimination', minStars: 4 },
  ]},
  { id: 'bathroom', label: 'Bathroom', icon: '◎', facility: null, items: [
    { id: 'BTH-01', label: 'No mold, mildew, or drain odor', minStars: 4 },
    { id: 'BTH-02', label: 'Strong water pressure, stable temperature', minStars: 4 },
    { id: 'BTH-03', label: 'Towels fresh and plentiful', minStars: 4 },
    { id: 'BTH-04', label: 'Luxury amenity brands present', minStars: 5 },
    { id: 'BTH-05', label: 'Deep bathtub present and clean', minStars: 5 },
    { id: 'BTH-06', label: 'Rainfall shower or premium showerhead', minStars: 5 },
    { id: 'BTH-07', label: 'Heated floors or towel rails', minStars: 6 },
  ]},
  { id: 'breakfast', label: 'Breakfast', icon: '☀', facility: 'hasRestaurant', items: [
    { id: 'BRK-01', label: 'Hot items fresh and at correct temperature', minStars: 4 },
    { id: 'BRK-02', label: 'Good variety — hot, cold, pastry, fruit', minStars: 4 },
    { id: 'BRK-03', label: 'Coffee quality high — espresso or equivalent', minStars: 4 },
    { id: 'BRK-04', label: 'Fresh juice — not from concentrate', minStars: 4 },
    { id: 'BRK-05', label: 'Refills fast — coffee, juice, bread', minStars: 4 },
    { id: 'BRK-06', label: 'Local or regional items featured', minStars: 4 },
    { id: 'BRK-07', label: 'Vegan and plant-based options clearly labeled', minStars: 4 },
    { id: 'BRK-08', label: 'Gluten-free options available', minStars: 4 },
    { id: 'BRK-09', label: 'Allergen information accessible', minStars: 4 },
    { id: 'BRK-10', label: 'A la carte or cooked-to-order station', minStars: 5 },
    { id: 'BRK-11', label: 'In-room breakfast well-executed', minStars: 5 },
    { id: 'BRK-12', label: 'Personalized dietary preferences remembered', minStars: 6 },
    { id: 'BRK-13', label: 'Overall food quality high', minStars: 4 },
    { id: 'BRK-14', label: 'Buffet and/or à la carte clearly presented', minStars: 4 },
  ]},
  { id: 'lunch', label: 'Lunch & All-Day Dining', icon: '◑', facility: 'hasRestaurant', items: [
    { id: 'LUN-01', label: 'Menu available and easy to navigate', minStars: 4 },
    { id: 'LUN-02', label: 'Food fresh — not reheated or tired', minStars: 4 },
    { id: 'LUN-03', label: 'Good variety — light dishes, mains, snacks', minStars: 4 },
    { id: 'LUN-04', label: 'Vegan and vegetarian options available', minStars: 4 },
    { id: 'LUN-05', label: 'Gluten-free options available', minStars: 4 },
    { id: 'LUN-06', label: 'Menu reflects local cuisine or culture', minStars: 4 },
    { id: 'LUN-07', label: 'Portion sizes appropriate for price point', minStars: 4 },
    { id: 'LUN-08', label: 'Seasonal or market-driven menu', minStars: 5 },
    { id: 'LUN-09', label: 'Chef visible or kitchen open concept', minStars: 5 },
    { id: 'LUN-10', label: 'Menu physically clean and in good condition', minStars: 4 },
  ]},
  { id: 'restaurant', label: 'Restaurant & Dinner', icon: '◇', facility: 'hasRestaurant', items: [
    { id: 'RST-01', label: 'Food fresh and at correct temperature', minStars: 4 },
    { id: 'RST-02', label: 'Presentation attractive and consistent', minStars: 4 },
    { id: 'RST-03', label: 'Menu diverse — meat, fish, vegetarian', minStars: 4 },
    { id: 'RST-04', label: 'Vegan options available and well-executed', minStars: 4 },
    { id: 'RST-05', label: 'Authentic or locally-inspired cuisine', minStars: 4 },
    { id: 'RST-06', label: 'Menu not generic — not hotel safe food', minStars: 4 },
    { id: 'RST-07', label: 'Ingredients described — origin or sourcing noted', minStars: 5 },
    { id: 'RST-08', label: 'Sommelier or beverage specialist present', minStars: 5 },
    { id: 'RST-09', label: 'Wine list curated and appropriate for category', minStars: 5 },
    { id: 'RST-10', label: 'Tasting menu or chefs table available', minStars: 6 },
    { id: 'RST-11', label: 'Michelin star or recognized culinary identity', minStars: 6 },
    { id: 'RST-12', label: 'Food cooked to correct doneness — not under or overcooked', minStars: 4 },
  ]},
  { id: 'fbservice', label: 'F&B Service', icon: '◈', facility: 'hasRestaurant', items: [
    { id: 'FBS-01', label: 'Greeted and seated promptly', minStars: 4 },
    { id: 'FBS-02', label: 'Order taken within 5 minutes', minStars: 4 },
    { id: 'FBS-03', label: 'Staff knowledgeable about the menu', minStars: 4 },
    { id: 'FBS-04', label: 'Allergies and dietary needs taken seriously', minStars: 4 },
    { id: 'FBS-05', label: 'Tables cleared promptly between courses', minStars: 4 },
    { id: 'FBS-06', label: 'Water refilled without being asked', minStars: 4 },
    { id: 'FBS-07', label: 'Staff able to recommend dishes confidently', minStars: 5 },
    { id: 'FBS-08', label: 'Pacing between courses well-managed', minStars: 5 },
    { id: 'FBS-09', label: 'Bill presented discreetly and accurately', minStars: 4 },
    { id: 'FBS-10', label: 'Farewell warm — not transactional', minStars: 4 },
  ]},
  { id: 'pool', label: 'Pool', icon: '≈', facility: 'hasPool', items: [
    { id: 'PL-01', label: 'Water temperature comfortable (28-30 C)', minStars: 4 },
    { id: 'PL-02', label: 'Deck clean — no abandoned towels', minStars: 4 },
    { id: 'PL-03', label: 'Chlorine within acceptable range', minStars: 4 },
    { id: 'PL-04', label: 'Seating adequate relative to hotel room count', minStars: 4 },
    { id: 'PL-05', label: 'Towels stocked at poolside', minStars: 4 },
    { id: 'PL-06', label: 'Pool attendant present and attentive', minStars: 5 },
    { id: 'PL-07', label: 'Poolside beverage service available', minStars: 5 },
    { id: 'PL-08', label: 'Architectural or infinity pool design', minStars: 6 },
    { id: 'PL-09', label: 'Pool overall clean and well maintained', minStars: 4 },
    { id: 'PL-10', label: 'Water clarity good', minStars: 4 },
    { id: 'PL-11', label: 'Family-friendly features present (kids pool/splash area)', minStars: 4 },
    { id: 'PL-12', label: 'Waterslides present and functioning (if applicable)', minStars: 5 },
  ]},
  { id: 'spa', label: 'Spa & Wellness', icon: '✦', facility: 'hasSpa', items: [
    { id: 'SP-01', label: 'Relaxing atmosphere from entrance', minStars: 4 },
    { id: 'SP-02', label: 'Locker rooms clean and well-stocked', minStars: 4 },
    { id: 'SP-03', label: 'No hair in drains', minStars: 4 },
    { id: 'SP-04', label: 'Sauna functioning properly', minStars: 4 },
    { id: 'SP-05', label: 'Staff knowledgeable about treatments', minStars: 4 },
    { id: 'SP-06', label: 'Premium product brands used in treatments', minStars: 5 },
    { id: 'SP-07', label: 'Thermal journey or circuit available', minStars: 6 },
    { id: 'SP-08', label: 'Bespoke treatment programming', minStars: 6 },
    { id: 'SP-09', label: 'Sauna, steam room, infrared or similar present', minStars: 4 },
    { id: 'SP-10', label: 'Interior lighting appropriate', minStars: 4 },
    { id: 'SP-11', label: 'Massage/treatments offered', minStars: 4 },
    { id: 'SP-12', label: 'Treatment quality (if a treatment was received — describe in notes)', minStars: 4 },
    { id: 'SP-13', label: 'Guest privacy and dignity protected during treatments and in changing areas', minStars: 4 },
  ]},
  { id: 'housekeeping', label: 'Housekeeping', icon: '⌂', facility: null, items: [
    { id: 'HK-01', label: 'Room cleaned on time', minStars: 4 },
    { id: 'HK-02', label: 'Proper restocking of amenities', minStars: 4 },
    { id: 'HK-03', label: 'Guest belongings respected and undisturbed', minStars: 4 },
    { id: 'HK-04', label: 'Hallway noise minimal during service', minStars: 4 },
    { id: 'HK-05', label: 'Staff appearance professional', minStars: 4 },
    { id: 'HK-06', label: 'Turndown service with personal touch', minStars: 5 },
    { id: 'HK-07', label: 'Nightly gift or handwritten note', minStars: 6 },
  ]},
  { id: 'departure', label: 'Departure', icon: '←', facility: null, items: [
    { id: 'DEP-01', label: 'Billing accurate and clearly itemized', minStars: 4 },
    { id: 'DEP-02', label: 'Checkout completed under 3 minutes', minStars: 4 },
    { id: 'DEP-03', label: 'Warm farewell — guest addressed by name', minStars: 4 },
    { id: 'DEP-04', label: 'Luggage assistance offered', minStars: 4 },
    { id: 'DEP-05', label: 'Invitation to return', minStars: 4 },
    { id: 'DEP-06', label: 'Loyalty program or return offer presented', minStars: 5 },
    { id: 'DEP-07', label: 'Personalised farewell gift or gesture', minStars: 6 },
  ]},
];
